# Digital Recognition Notebook

## Neural Network

In [3]:
# import keras
import keras as kr

model = kr.models.Sequential()

model.add(kr.layers.Dense(units=1000, activation='relu', input_dim=784))

model.add(kr.layers.Dense(units=10, activation='softmax'))

model.compile(loss='catagorical_crossentropy', optimizer='sgd', metrics=['accuracy'])

Using TensorFlow backend.


ModuleNotFoundError: No module named 'tensorflow'

In [3]:
import gzip

# This opens the images file which is located in our local directory and assigns the read in value to a variable
with gzip.open('t10k-images-idx3-ubyte.gz', 'rb') as f:
    image_content = f.read()
    
with gzip.open('t10k-labels-idx1-ubyte.gz', 'rb') as f:
    label_content = f.read()

In [7]:
import numpy as np

image = ~np.array(list(image_content[16:])).reshape(10000,28,28).astype(np.uint8)

# Display the bytes as 1s and 0s in an array
print((~image[0]).astype(np.bool).astype(np.uint8))

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 

In [2]:
import sklearn.preprocessing as pre
print(pre)

<module 'sklearn.preprocessing' from 'D:\\Anaconda3\\lib\\site-packages\\sklearn\\preprocessing\\__init__.py'>
