<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/NumPy_logo.svg/1200px-NumPy_logo.svg.png" width="200px" height="100px">

# Notebook on NumPy

##### Ryan Conway

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. Its main object is the homogeneous multidimensional array, a table of values, all of the same type, indexed by a tuple of positive integers.


## Arrays

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.


In [9]:
#Array creation:
#Import numpy
import numpy as np
#Assign "a" a value of a numpy array
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [5]:
#Describe the data type of the array
a.dtype

dtype('int32')

In [7]:
#Assign "b" a value of a numpy array, populated with decimal
b = np.array([1.2, 3.4, 5.6, 7.8, 9.11])
#Describe the data type of the array
b.dtype

dtype('float64')

In [10]:
#To print the contents of the array, you can display them with "print"
print(a)

[1 2 3 4 5]


## NumPy Random

Numpy random is used to generate random sampling. An important part of any simulation is the ability to generate random numbers. For this purpose, NumPy provides various routines in the submodule random. It uses a particular algorithm, called the Mersenne Twister, to generate pseudorandom numbers.

In [4]:
#Import the numpy Library
import numpy as np

#Creates an array of the given shape and populate it with random samples from a uniform distribution
np.random.rand(3,2)


array([[0.83971875, 0.92214767],
       [0.67113951, 0.08844794],
       [0.14561268, 0.82956272]])

## Random_Sample

The random_sample method returns random floats in the half-open interval [0.0, 1.0].

Results are from the “continuous uniform” distribution over the stated interval.

In [5]:
#Generates a random float
np.random.random_sample()

0.13225220698107854

In [8]:
#Generates an array of random floats (Size of the array is specified)
np.random.random_sample((7))

array([0.31019309, 0.00210643, 0.55935572, 0.99123498, 0.83300803,
       0.08127137, 0.06930816])